version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = false

  # [[blocks.segments]]
  #   leading_diamond = ''
  #   template = '{{ .Icon }} {{ .HostName }} '
  #   foreground = '#00c983'
  #   background = '#003543'
  #   type = 'os'
  #   style = 'diamond'

  [[blocks.segments]]
    template = ' <#000> </> {{ .Path }} '
    foreground = '#ffffff'
    leading_diamond = ''
    background = '#DA627D'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = '\'
      home_icon = ''
      style = 'full'

  [[blocks.segments]]
    template = ' ➜ {{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FCA17D'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      branch_icon = ' <#ffffff> </>'
      fetch_stash_count = true
      fetch_status = false
      fetch_upstream_icon = true

  # [[blocks.segments]]
  #   template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
  #   foreground = '#ffffff'
  #   powerline_symbol = ''
  #   background = '#76b367'
  #   type = 'node'
  #   style = 'powerline'

  # [[blocks.segments]]
  #   template = '  {{ .FormattedMs }} '
  #   foreground = '#ffffff'
  #   powerline_symbol = ''
  #   background = '#83769c'
  #   type = 'executiontime'
  #   style = 'powerline'
  #
  #   [blocks.segments.properties]
  #     always_enabled = true
  #
  # [[blocks.segments]]
  #   template = '  {{ .CurrentDate | date .Format }} '
  #   foreground = '#ffffff'
  #   powerline_symbol = ''
  #   background = '#33658A'
  #   type = 'time'
  #   style = 'powerline'
  #
  #   [blocks.segments.properties]
  #     time_format = '3:04 PM'
  #
  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#2e9599'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

# [[blocks]]
#   type = 'prompt'
#   alignment = 'left'
#   newline = true

  [[blocks.segments]]
    template = ' '
    foreground = '#cd5e42'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = ' <#26C6DA>❯</><#45F1C2>❯</>'
    # template = ' <#45F1C2><b>⚡</b></><b>{{ .UserName }}</b> <#26C6DA>❯</><#45F1C2>❯</>'
    foreground = '#CD4277'
    type = 'text'
    style = 'plain'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'
  newline = false

[[blocks.segments]]
    template = '   {{ .CurrentDate | date .Format }} '
    foreground = '#ffffff'
    background = '#33658A'
    leading_diamond = ''
    trailing_diamond = ''
    type = 'time'
    style = 'diamond'

    [blocks.segments.properties]
      time_format = '15:04'

[transient_prompt]
template = ' <#26C6DA>❯</><#45F1C2>❯</> '
