console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#5C5F77'
  blue = '#1E66F5'
  closer = 'p:os'
  cyan = '#179299'
  green = '#40A02B'
  grey = '#E5E5E6'
  lavender = '#7287FD'
  magenta = '#EA76CB'
  orange = '#fe640b'
  os = '#ACB0BE'
  pink = '#ea76cb'
  purple = '#8839ef'
  red = '#D20F39'
  text = 'p:wight'
  white = '#ACB0BE'
  wight = '#FFFFFF'
  yellow = '#DF8E1D'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[transient_prompt]
  template = '<p:pink,transparent></><,p:pink> {{ .Folder }} </><p:pink,transparent></> '
  foreground = 'p:wight'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'p:text'
    background = 'p:blue'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ path .Path .Location }} '
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:pink'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:text'
    background = 'p:lavender'
    type = 'git'
    style = 'diamond'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:cyan{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:lavender{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = ' '
    foreground = 'p:green'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:blue'
    background = 'transparent'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = false

  [[blocks.segments]]
    template = 'in <p:blue><b>{{ .Name }}</b></> '
    foreground = 'p:white'
    background = 'transparent'
    type = 'shell'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
    foreground = 'p:white'
    background = 'transparent'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:white'
  background = 'p:orange'
  type = 'aws'
  style = 'diamond'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  style = 'diamond'
  tips = ['az']

  [tooltips.properties]
    display_default = true
